version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/pytest-circleci

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: run linter and tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
